// The audit of the fork: checks in one go everything the plan promises.
// Every claim in the README and in the plan has its check here.
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

let failures = 0;
const ok = (n, c, extra = '') => {
  console.log(`  ${c ? 'OK   ' : 'FAIL '} ${n}${extra ? ' · ' + extra : ''}`);
  if (!c) failures++;
};
const section = (t) => console.log(`\n== ${t}`);
// What depends on someone else's service cannot bring the battery down: if it
// could not be checked it is said, but it does not count as a failure of ours.
const warning = (n, extra = '') => console.log(`  WARN  ${n}${extra ? ' · ' + extra : ''}`);
const run = (cmd, env) => {
  const options = { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], env: { ...process.env, ...env } };
  try {
    return { output: execSync(cmd, options), exitCode: 0 };
  } catch (e) {
    return { output: (e.stdout ?? '') + (e.stderr ?? ''), exitCode: e.status ?? 1 };
  }
};
const read = (f) => fs.readFileSync(f, 'utf8');

/**
 * `npm --json` does not guarantee that the output is only JSON: since September
 * 2026 npm interleaves notices like "npm notice This endpoint is being retired"
 * and `JSON.parse` of the whole output blows up. That took the CI down on all
 * three platforms with nothing in the project changed, so the object is
 * extracted here instead of trusting it to come clean.
 */
const json = (output) => {
  const i = output.indexOf('{');
  const f = output.lastIndexOf('}');
  if (i < 0 || f < i) {
    return {};
  }
  try {
    return JSON.parse(output.slice(i, f + 1));
  } catch {
    return {};
  }
};

section('identity');
const pkg = JSON.parse(read('package.json'));
ok('the name is the original one and the publisher is ours', pkg.name === 'restclient' && pkg.publisher === 'vscode-restclient');
ok('it is published for free', pkg.pricing === 'Free');
// `onLanguage:markdown` is there for the ```http blocks inside markdown, which is
// a real feature. The unacceptable one would be `*`: always on, no matter what.
ok('it does not activate on every start-up', !(pkg.activationEvents ?? []).includes('*'), `events: ${JSON.stringify(pkg.activationEvents)}`);
ok('it still contributes the http language', pkg.contributes.languages?.some((l) => l.id === 'http'));
// The public commands are REST Client's original API, restored at the
// organisation's request (issue #1): the exact list is frozen by
// src/test/integration/suite/commandIds.test.ts; here the shape is watched.
ok('the public commands carry the original prefix', pkg.contributes.commands.length === 21 && pkg.contributes.commands.every((c) => c.command.startsWith('rest-client.')), pkg.contributes.commands.map((c) => c.command).filter((c) => !c.startsWith('rest-client.')).join(', '));
ok('the runner is published as a binary', pkg.bin?.restclient !== undefined, pkg.bin?.restclient);

section('credit to the original author (it is MIT, but it is said)');
const readme = read('README.md');
ok('the README names Huachao Mao', readme.includes('Huachao Mao'));
ok('the README links to the original repository', readme.includes('github.com/Huachao/vscode-restclient'));
ok('the original MIT license is kept', read('LICENSE').includes('MIT'));

section('copyright: what each license demands is met');
const licenseText = read('LICENSE');
ok('the original copyright notice is verbatim', licenseText.includes('Copyright (c) 2016 - present Huachao Mao'));
ok('the MIT permission notice is complete', licenseText.includes('The above copyright notice and this permission notice shall be included'));
ok('the manifest credits the original author', JSON.stringify(pkg.contributors ?? []).includes('Huachao Mao'));
ok('the declared license is MIT', pkg.license === 'MIT');
// BSD and Apache require the notice to be reproduced in the binary distribution;
// the webpack bundle only keeps the /*! */ comments, so a file with the license
// of every production package travels along as well.
const notices = fs.existsSync('THIRD-PARTY-NOTICES.txt') ? read('THIRD-PARTY-NOTICES.txt') : '';
ok('the third-party notices file exists', notices.length > 0);
// The file is generated by scripts/generate-notices.mjs: if someone adds a
// dependency and does not regenerate it, they hear it here rather than from a lawyer.
ok('the third-party notices are up to date (generate-notices --check)', run('node scripts/generate-notices.mjs --check').exitCode === 0);
const tree = json(run('npm ls --omit=dev --all --json').output);
const packages = new Set();
// No version = optional dependency npm did not install; it does not ship, it does not count.
const walkTree = (node) => { for (const [n, v] of Object.entries(node?.dependencies ?? {})) { if (v.version) { packages.add(`${n}@${v.version}`); walkTree(v); } } };
walkTree(tree);
const withoutNotice = [...packages].filter((pq) => !notices.includes(`\n${pq}\n`));
ok('every production package has its notice', packages.size > 0 && withoutNotice.length === 0, withoutNotice.length ? withoutNotice.slice(0, 5).join(', ') : `${packages.size} packages`);
const copyleft = [...notices.matchAll(/^License: (.+)$/gm)].map((m) => m[1]).filter((l) => /GPL|SSPL|UNKNOWN|UNLICENSED|CC-BY-NC|EUPL|OSL/i.test(l));
ok('no copyleft or unknown license', copyleft.length === 0, copyleft.join(', '));

section('assets of our own (nobody else\'s image is inherited)');
ok('the declared icon exists', fs.existsSync(pkg.icon ?? ''), pkg.icon);
const images = fs.existsSync('images') ? fs.readdirSync('images') : [];
ok('without the original project\'s icon', !images.includes('rest_icon.png'));
ok('without the original\'s demo gifs', !images.some(f => /demo|response|code-snippet|usage/.test(f)), images.join(', '));

section('privacy: it talks to nobody');
ok('no telemetry dependency', !JSON.stringify(pkg.dependencies).includes('applicationinsights'));
const withTelemetry = run('git grep -l "applicationinsights\\|trackEvent\\|AiKey" -- src').output.trim();
ok('no trace of telemetry in the code', withTelemetry === '', withTelemetry);
ok('no telemetry setting in the manifest', !JSON.stringify(pkg.contributes.configuration).includes('Telemetry'));

section('dependencies');
// `npm audit` goes out to the network on every run: if the registry is slow,
// down, or changes its format, that is not this repository's problem. It gets a
// time limit and, without data, it ends as a warning instead of failing the CI.
const audit = json(run('npm audit --omit=dev --json --fetch-timeout=60000').output);
const v = audit.metadata?.vulnerabilities ?? {};

// Exceptions: advisories that CANNOT be fixed today and that we do not reach.
// Each carries its why, and the check below expires them by itself as soon as
// a fix appears, so that none stays here out of inertia.
const EXCEPTIONS = {
  // (empty) On 2026-10-03 there were three entries for http-cache-semantics
  // <=4.2.0, with no fix published and out of reach (got only uses
  // cacheable-request with options.cache). The next day 4.3.0 came out and this
  // very check demanded their removal. That is how an exception should die.
};

if (typeof v.total === 'number') {
  const packages = Object.keys(audit.vulnerabilities ?? {});
  const unexcused = packages.filter((n) => !EXCEPTIONS[n]);
  ok(
    'no production vulnerability without a written exception',
    unexcused.length === 0,
    unexcused.length ? unexcused.join(', ') : `${packages.length} with an exception, 0 without`
  );

  // An exception stops being valid as soon as there is a fix. `fixAvailable`
  // as an object with isSemVerMajor is npm proposing a downgrade: that does not count.
  for (const n of packages.filter((x) => EXCEPTIONS[x])) {
    const fix = audit.vulnerabilities[n]?.fixAvailable;
    const fixable = fix === true || (fix && typeof fix === 'object' && !fix.isSemVerMajor);
    ok(
      `the exception for ${n} is still needed`,
      !fixable,
      fixable ? `there is a fix now (${JSON.stringify(fix)}): remove it and update` : EXCEPTIONS[n].why.slice(0, 80)
    );
  }
} else {
  warning('production vulnerabilities: npm audit returned no data', 'no network or unexpected format');
}
ok('aws-amplify is out', !JSON.stringify(pkg.dependencies).includes('aws-amplify'));
ok('unmaintained xmldom is out', pkg.dependencies.xmldom === undefined);

section('the core does not depend on the editor');
for (const f of ['src/cli/index.ts', 'src/cli/mcp.ts', 'src/cli/minimalParser.ts', 'src/core/sequence.ts', 'src/core/assertions.ts', 'src/core/jetBrainsEnvironments.ts', 'src/core/imports.ts', 'src/core/sse.ts', 'src/core/websocket.ts', 'src/core/junit.ts', 'src/utils/httpClient.ts']) {
  const r = run(`node scripts/track-vscode.mjs ${f}`);
  ok(`${path.basename(f)} does not drag vscode in`, r.exitCode === 0, r.exitCode === 0 ? '' : r.output.split('\n')[0]);
}
const compiled = fs.existsSync('dist-cli/cli/index.js');
ok('the runner is compiled', compiled);
if (compiled) {
  const loaded = fs.readdirSync('dist-cli', { recursive: true }).filter((f) => String(f).endsWith('.js'));
  ok('the runner does not bundle editor controllers', !loaded.some((f) => String(f).includes('controllers')), loaded.length + ' files');
}

section('the resources the code asks for exist and ship');
// Three real failures came out of here: a half-renamed css, the webview's js
// excluded from the package and an inherited icon that no longer existed. None
// breaks the build; they show up when opening the response tab once installed.
const resources = [...read('src/views/baseWebview.ts').matchAll(/asAbsolutePath\(path\.join\('([^']+)', '([^']+)'\)\)/g)]
  .map((m) => `${m[1]}/${m[2]}`);
ok('the code asks for resources by path', resources.length > 0, resources.join(', '));
for (const r of resources) {
  ok(`${r} exists`, fs.existsSync(r));
}

section('the rename left no loose ends');
// The fork renamed commands and settings. What was left half done does not
// break the build: a document link called `rest-client._openDocumentLink` and,
// with REST Client installed, the other extension opened it.
const sources = run('git ls-files src').output.split(/\r?\n/).filter((f) => f.endsWith('.ts') && !f.startsWith('src/test'));
const registered = new Set([...read('package.json').matchAll(/"command":\s*"([^"]+)"/g)].map((m) => m[1]));
for (const f of sources) {
  for (const m of read(f).matchAll(/registerCommand(?:Safely)?\('([^']+)'/g)) registered.add(m[1]);
}
const invoked = new Set();
for (const f of sources) {
  for (const m of read(f).matchAll(/command:([a-z0-9-]+\.[A-Za-z0-9._-]+)/g)) invoked.add(m[1]);
}
const orphans = [...invoked].filter((c) => !registered.has(c));
ok('every command invoked through a link exists', orphans.length === 0, orphans.join(', '));

// Only the hyphenated strings are looked at: the internal identifiers
// (RestClientSettings and company) are left as they are so that patches from
// the original project keep applying without noise.
// The identifier the code announces has to be the one the manifest publishes:
// otherwise `extensions.getExtension(...)` returns undefined and the extension
// cannot find itself (it happened when the fork was renamed).
// Single or double quotes: nobody's formatter should blind the check.
const declaredId = /ExtensionId: string = ['"]([^'"]+)['"]/.exec(read('src/common/constants.ts'))?.[1];
ok('the id in the code is the manifest\'s publisher.name', declaredId === `${pkg.publisher}.${pkg.name}`, `${declaredId} vs ${pkg.publisher}.${pkg.name}`);

// The Marketplace may refuse to CREATE an extension whose `name` another
// publisher already uses, even if the full publisher.name identifier is free.
// It happened on 2026-09-28: 1.2.0 passed the whole battery in CI and died at
// the publish step with "The extension 'rest-client' already exists in the
// Marketplace". Eleven minutes to find out something that takes a second to ask.
// That duplicates exist proves nothing: the ones there are inherited (humao
// 2016, s-kainet 2018) and I found none whose newest member is from 2022 or
// later. Until we are published, someone else holding the name is a failure;
// once published, we show up in the list and the check passes.
const queryGallery = async (text) => {
    const r = await fetch('https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Accept: 'application/json;api-version=7.2-preview.1' },
        body: JSON.stringify({ filters: [{ criteria: [{ filterType: 10, value: text }], pageSize: 200 }], flags: 914 }),
        signal: AbortSignal.timeout(10000),
    });
    if (!r.ok) { throw new Error('HTTP ' + r.status); }
    return (await r.json())?.results?.[0]?.extensions ?? [];
};
try {
    const sameName = (await queryGallery(pkg.name)).filter((e) => e.extensionName === pkg.name);
    const ours = sameName.find((e) => e.publisher?.publisherName?.toLowerCase() === pkg.publisher.toLowerCase());
    const others = sameName.filter((e) => e !== ours);
    if (ours) {
        ok(`the Marketplace already knows ${pkg.publisher}.${pkg.name}`, true, `published, v${ours.versions?.[0]?.version ?? '?'}`);
    } else {
        ok(
            `the name "${pkg.name}" is free to create the extension`,
            others.length === 0,
            others.length ? `used by ${others.map((e) => `${e.publisher.publisherName} (${String(e.publishedDate).slice(0, 7)})`).join(', ')} — publishing would fail with "already exists"` : 'no other publisher uses it'
        );
    }
} catch (e) {
    warning('could not query the Marketplace for the name', e.message);
}

section('level 2: JetBrains format, streaming, agents and runner');
const cliSource = read('src/cli/index.ts');
ok('the runner understands --env, --secret, --junit and --timeout', ['--env', '--secret', '--junit', '--timeout'].every((o) => cliSource.includes(`'${o}'`)));
ok('the runner reads http-client.env.json and import/run', cliSource.includes('environmentsFolder') && cliSource.includes('resolveRun'));
const selectorSource = read('src/utils/selector.ts');
ok('the editor resolves run #name and skips the import lines', selectorSource.includes('resolveRun') && selectorSource.includes('isImportLine'));
const systemVariables = read('src/utils/httpVariableProviders/systemVariableProvider.ts');
ok('the editor has $secret and the JetBrains aliases', systemVariables.includes('SecretVariableName') && systemVariables.includes('UuidVariableName') && systemVariables.includes('IsoTimestampVariableName'));
const controller = read('src/controllers/requestController.ts');
ok('the panel paints text/event-stream as it arrives', controller.includes('startStreaming') && controller.includes('appendChunk'));

// The extension and the response webview talk through postMessage, and the
// webview side (webview/main.js) is plain JavaScript that nothing type-checks.
// During the English pass a variable rename turned `{ command: 'trozo', texto }`
// into `{ command: 'trozo', text }` while main.js kept reading `message.texto`:
// every streamed chunk would have rendered as "undefined", and all 68 tests
// stayed green. So the contract is written down here and both sides are held
// to it, textually, on every run. A new message means a new line in CONTRACT.
//
// It is a textual guard and it is strict on purpose: it knows one way of
// sending (`postMessage({ command: '…', key: value })`) and one way of reading
// (`message.command === '…'`, `message.key`), and anything else fails it rather
// than slipping past. What it cannot see is WHICH command a key is read under:
// swapping `message.text` and `message.note` in main.js would pass.
{
  const CONTRACT = { chunk: ['text'], end: ['note'], foldAll: [], unfoldAll: [] };
  const withoutComments = (t) => t.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|\s)\/\/.*$/gm, '$1');
  const extensionSide = withoutComments(read('src/views/httpResponseWebview.ts'));
  const web = withoutComments(read('webview/main.js'));
  const sent = [...extensionSide.matchAll(/postMessage\(\{([^}]*)\}\)/g)].map((m) => {
    const literalBody = m[1];
    const commandName = /['"]?command['"]?\s*:\s*['"]([^'"]+)['"]/.exec(literalBody)?.[1];
    const messageKeys = [...literalBody.matchAll(/(?:^|,)\s*['"]?([A-Za-z_]\w*)['"]?\s*(?=:|,|$)/g)].map((k) => k[1]).filter((k) => k !== 'command');
    return { commandName, messageKeys, odd: /\.\.\.|\[/.test(literalBody) };
  });
  const shape = (o) => JSON.stringify(Object.keys(o).sort().map((k) => [k, [...o[k]].sort()]));
  const byCommand = Object.fromEntries(sent.map((e) => [e.commandName, e.messageKeys]));
  const nPost = (extensionSide.match(/postMessage\(/g) ?? []).length;
  // Every postMessage call has to be one this guard can read: an object
  // literal with a literal command, no spread, no computed key, and no command
  // sent from two places (the second would hide the first).
  ok('the guard understands every postMessage of the extension', sent.length === nPost && sent.every((e) => e.commandName && !e.odd) && new Set(sent.map((e) => e.commandName)).size === sent.length, `${sent.length} of ${nPost}`);
  ok('the extension sends exactly the messages of the contract', shape(byCommand) === shape(CONTRACT), shape(byCommand));

  // The webview handles `unfoldAll` by elimination (anything that is not
  // `foldAll`), so it need not name every command; but each one it does name
  // has to exist, and the three it tells apart have to be there.
  const compared = [...web.matchAll(/message\.command\s*===\s*['"]([^'"]+)['"]/g)].map((m) => m[1]);
  const handled = [...new Set(compared)];
  ok('every command the webview checks is in the contract', handled.length >= 3 && handled.every((o) => Object.hasOwn(CONTRACT, o)), handled.join(', '));
  // Every mention of message.command has to be one of those comparisons: a
  // `!==`, a `switch` or a lookup table would name a command unseen.
  const mentions = (web.match(/message\s*\??\.\s*command/g) ?? []).length;
  ok('the webview only compares the command with === and a literal', mentions === compared.length, `${compared.length} of ${mentions}`);
  const readKeys = [...new Set([...web.matchAll(/message\.([A-Za-z_]\w*)/g)].map((m) => m[1]).filter((k) => k !== 'command'))].sort();
  const inContract = [...new Set(Object.values(CONTRACT).flat())].sort();
  ok('the webview reads exactly the keys of the contract', JSON.stringify(readKeys) === JSON.stringify(inContract), readKeys.join(', '));
  // The message is read as `const message = event.data;` and then `message.x`,
  // nothing else: no alias, no destructuring, no bracket or optional access.
  const otherForm = /message\s*\[|message\?\.|switch\s*\(\s*message|\}\s*=\s*message\b|\}\s*=\s*event\.data|event\.data\s*[.[?]|[^=!]=\s*message\s*[;,)\n]/.test(web);
  ok('the webview does not read the message in a way this guard cannot see', !otherForm && (web.match(/event\.data/g) ?? []).length === 1);

  // The same kind of contract, through the DOM: every id and attribute that
  // main.js looks up by name has to be written into the page by the extension.
  // The lists are exact, so a new lookup has to be added here knowingly.
  const writes = (attribute) => new RegExp(`(?<![\\w-])${attribute}="`).test(extensionSide);
  const attributes = [...new Set([...web.matchAll(/(?:hasAttribute|getAttribute|getNamedItem)\(\s*['"]([^'"]+)['"]/g)].map((m) => m[1]))].sort();
  const ids = [...new Set([...web.matchAll(/getElementById\(\s*['"]([^'"]+)['"]/g)].map((m) => m[1]))].sort();
  const unwritten = [...attributes.filter((a) => !writes(a)), ...ids.filter((i) => !extensionSide.includes(`id="${i}"`))];
  ok('every id and attribute the webview looks up, the extension writes',
    unwritten.length === 0 && JSON.stringify(attributes) === JSON.stringify(['range-end', 'range-start', 'start']) && JSON.stringify(ids) === JSON.stringify(['stream']),
    unwritten.length ? `not written: ${unwritten.join(', ')}` : [...attributes, ...ids].join(', '));
}
// And through argv: the editor launches the MCP server of the bundled runner.
ok('the editor launches the MCP server with the option the runner reads', read('src/utils/lmTools.ts').includes("'mcp', '--root'") && read('src/cli/index.ts').includes("=== '--root'"));
// And through the environment: the audit points the runner's own test at the
// published bundle. If the test stopped reading the variable it would quietly
// test the other build and come back green.
ok('the runner tests read the path the audit hands them', read('scripts/test-cli.mjs').includes('process.env.CLI_RUTA') && read('scripts/test-mcp.mjs').includes('process.env.CLI_RUTA'));
// And through stdout: the test servers announce their port as JSON and five
// readers parse it untyped. One of them was renamed alone during the English
// pass (`.puerto` -> `.port`) and every integration test timed out.
{
  const announcers = ['scripts/test-server.cjs', 'scripts/test-vsix.mjs', 'scripts/demo/launch.mjs'];
  const readers = ['scripts/test-cli.mjs', 'scripts/test-mcp.mjs', 'scripts/test-vsix.mjs', 'scripts/demo/launch.mjs', 'src/test/integration/runTest.ts'];
  const wrong = [
    ...announcers.filter((f) => !read(f).includes('JSON.stringify({ port: s.address().port })')),
    ...readers.filter((f) => !read(f).includes('JSON.parse(d.toString()).port)')),
  ];
  ok('the test servers and their readers agree on the port key', wrong.length === 0, wrong.join(', '));
}
ok('WEBSOCKET is handled in the editor and in the runner', controller.includes("'WEBSOCKET'") && read('src/cli/minimalParser.ts').includes("'WEBSOCKET'"));
const tools = read('src/utils/lmTools.ts');
ok('the send tool for agents asks for confirmation', tools.includes('prepareInvocation') && tools.includes('confirmationMessages'));
ok('the tool rejects files outside the workspace', tools.includes('is outside the workspace'));
ok('the tools are declared in the manifest', (pkg.contributes.languageModelTools ?? []).length === 2 && (pkg.contributes.mcpServerDefinitionProviders ?? []).length === 1);
const mcp = read('src/cli/mcp.ts');
ok('the MCP server confines the root and does not write to disk', mcp.includes('insideRoot') && !/fs\.write|writeFileSync/.test(mcp));
const mcpTest = run('node scripts/test-mcp.mjs');
ok('the MCP server passes its end-to-end test', mcpTest.exitCode === 0, /===== (\d+) failures/.exec(mcpTest.output)?.[0] ?? '');
ok('the GitHub action exists and downloads the runner from the release', fs.existsSync('action.yml') && read('action.yml').includes('using: composite') && read('action.yml').includes('restclient.js'));
ok('the release workflow attaches the standalone runner', read('.github/workflows/release.yml').includes('restclient.js'));
// This audit runs the unit tests (out-test/) and the runner's (dist-cli/), so
// whoever launches it has to have compiled both first. The `publish` job of
// release-please.yml did not: on a clean checkout the audit failed and the
// publication would have stopped there. Nobody saw it because the two releases
// attempted so far went through release.yml.
{
  const workflows = fs.readdirSync('.github/workflows').filter((f) => /\.ya?ml$/.test(f));
  const withAudit = workflows.filter((f) => /^\s*(-\s+)?run:\s*npm run audit\s*$/m.test(read(`.github/workflows/${f}`)));
  const uncompiled = withAudit.filter((f) => {
    const before = read(`.github/workflows/${f}`).split(/^\s*(?:-\s+)?run:\s*npm run audit\s*$/m)[0];
    const step = (...scripts) => scripts.some((s) => new RegExp(`^[ \\t]*(?:-[ \\t]+)?run:\\s*(?:xvfb-run -a )?npm run ${s}\\s*$`, 'm').test(before));
    return !(step('compile-tests', 'test:unit', 'test:integration') && step('build:cli', 'test:cli'));
  });
  // It is a textual check: it recognises a `run: npm run <script>` step on its
  // own line, and looks at what comes before the audit in the file, not in the
  // job. If a workflow stops launching the audit that way, it fails too.
  const detail = withAudit.length < 3 ? `only ${withAudit.length} workflows launch the audit in a way this guard recognises: ${withAudit.join(', ')}`
    : uncompiled.length ? `without compiling first: ${uncompiled.join(', ')}` : withAudit.join(', ');
  ok('every workflow that launches the audit compiles the tests and the runner first', withAudit.length >= 3 && uncompiled.length === 0, detail);
}
const npmPkg = JSON.parse(read('npm/package.json'));
ok('the npm package has the same version number', npmPkg.version === pkg.version, `npm ${npmPkg.version} / extension ${pkg.version}`);
ok('the npm package is just the runner', npmPkg.bin?.restclient === 'cli.js' && JSON.stringify(npmPkg.files) === JSON.stringify(['cli.js', 'README.md', 'LICENSE']) && !npmPkg.dependencies);
ok('the grammar highlights import and run', read('syntaxes/http.tmLanguage.json').includes('http.import') && read('syntaxes/http.tmLanguage.json').includes('http.run'));

section('both languages are complete');
const l10n = run('node scripts/check-l10n.mjs');
ok('English and Spanish without gaps', l10n.exitCode === 0, /=+ (\d+) failures/.exec(l10n.output)?.[1] + ' failures');

section('the package carries what it promises and nothing else');
const packaged = run('npx vsce ls --no-dependencies').output.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
const inPackage = (f) => packaged.includes(f);
ok('the runner bundle ships in the package', inPackage('dist/cli.js'));
ok('the declared binary is the one that ships', inPackage(pkg.bin.restclient.replace('./', '')));
ok('the third-party notices ship', inPackage('THIRD-PARTY-NOTICES.txt') && inPackage('LICENSE'));
ok('both languages ship', inPackage('package.nls.json') && inPackage('package.nls.es.json'));
for (const r of resources) {
  ok(`${r} ships in the package`, inPackage(r));
}
ok('no source code inside', !packaged.some((f) => f.startsWith('src/')));
ok('no source maps inside', !packaged.some((f) => f.endsWith('.map')));
ok('no internal documents inside', !packaged.some((f) => f.startsWith('docs/') || f.startsWith('scripts/')));
ok('neither the npm package nor the action inside', !packaged.some((f) => f.startsWith('npm/') || f === 'action.yml'));
if (fs.existsSync('dist/cli.js')) {
  const cli = read('dist/cli.js');
  ok('the published runner starts on its own (shebang)', cli.startsWith('#!/usr/bin/env node'));
  ok('the published runner does not load the editor', !cli.includes('require("vscode")'));
  const r = run('node dist/cli.js');
  ok('the published runner explains its usage', r.exitCode === 2 && r.output.includes('usage:'));
}

section('it compiles and passes the tests');
ok('the code compiles', run('npx tsc -p ./ --noEmit --skipLibCheck').exitCode === 0);
ok('the runner compiles', run('npx tsc -p tsconfig.cli.json --noEmit').exitCode === 0);
const unit = run('npx mocha "out-test/test/unit/**/*.test.js"');
const nUnit = /(\d+) passing/.exec(unit.output)?.[1] ?? '0';
ok('unit tests green', unit.exitCode === 0 && Number(nUnit) >= 15, `${nUnit} tests`);
const cli = run('node scripts/test-cli.mjs');
ok('the runner passes its end-to-end test', cli.exitCode === 0, /===== (\d+) failures/.exec(cli.output)?.[0] ?? '');
const cliPub = run('node scripts/test-cli.mjs', { CLI_RUTA: 'dist/cli.js' });
ok('the published runner passes the same test', cliPub.exitCode === 0, /===== (\d+) failures/.exec(cliPub.output)?.[0] ?? '');

section('compatibility with REST Client');
const splitting = read('src/core/sequence.ts');
ok('splitting on ### behaves like the original', splitting.includes('getDelimiterRows'));

section('promises of the README');
// The number of tests is the first thing to go stale in a README, and here it
// is also the fork's central argument. It is counted, not believed.
const countIts = (dir) => fs.readdirSync(dir, { recursive: true })
  .filter((f) => String(f).endsWith('.test.ts'))
  .reduce((n, f) => n + (read(path.join(dir, String(f))).match(/\bit\(/g)?.length ?? 0), 0);
const nTests = countIts('src/test/unit') + countIts('src/test/integration');
for (const f of ['docs/HTTPKEEPER.md', 'docs/HTTPKEEPER.es.md']) {
  const promised = /\*\*(\d+)\*\*\s*\(/.exec(read(f))?.[1];
  ok(`${f} promises the number of tests there are`, Number(promised) === nTests, `says ${promised}, there are ${nTests}`);
}
ok('the unit tests that run are the ones written', Number(nUnit) === countIts('src/test/unit'), `${nUnit} running`);
ok('promises 400 packages', read('docs/HTTPKEEPER.md').includes('400') && readme.includes('400'));
ok('promises zero telemetry', read('docs/HTTPKEEPER.md').toLowerCase().includes('none') && readme.toLowerCase().includes('telemetry removed'));

console.log(`\n===== ${failures} failures`);
process.exit(failures ? 1 : 0);
